Traceback (most recent call last):
  File "C:\Users\Alexander\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Alexander\anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Alexander\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import matplotlib.mlab as mlab
import random 
import econml
import time
from patsy import dmatrices
from sklearn.linear_model import Lasso, LassoCV
from sklearn.model_selection import train_test_split
from scipy.stats import norm, expon, binom
from econml.grf import RegressionForest, CausalIVForest as instrumental_forest
from econml.dml import CausalForestDML as causal_forest
from econml.policy import PolicyForest, PolicyTree 
random.seed(12)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
[1;32mC:\Users\ALEXAN~1\AppData\Local\Temp/ipykernel_16224/679895507.py[0m in [0;36m<module>[1;34m[0m
[0;32m     16[0m [1;32mfrom[0m [0meconml[0m[1;33m.[0m[0mgrf[0m [1;32mimport[0m [0mRegressionForest[0m[1;33m,[0m [0mCausalIVForest[0m [1;32mas[0m [0minstrumental_forest[0m[1;33m[0m[1;33m[0m[0m
[0;32m     17[0m [1;32mfrom[0m [0meconml[0m[1;33m.[0m[0mdml[0m [1;32mimport[0m [0mCausalForestDML[0m [1;32mas[0m [0mcausal_forest[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 18[1;33m [1;32mfrom[0m [0meconml[0m[1;33m.[0m[0mpolicy[0m [1;32mimport[0m [0mPolicyForest[0m[1;33m,[0m [0mPolicyTree[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     19[0m [0mrandom[0m[1;33m.[0m[0mseed[0m[1;33m([0m[1;36m12[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\econml\policy\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;31m# Licensed under the MIT License.[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;33m[0m[0m
[1;32m----> 4[1;33m [1;32mfrom[0m [1;33m.[0m[0m_forest[0m [1;32mimport[0m [0mPolicyTree[0m[1;33m,[0m [0mPolicyForest[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [1;32mfrom[0m [1;33m.[0m[0m_drlearner[0m [1;32mimport[0m [0mDRPolicyTree[0m[1;33m,[0m [0mDRPolicyForest[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\econml\policy\_forest\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;31m# Licensed under the MIT License.[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;33m[0m[0m
[1;32m----> 4[1;33m [1;32mfrom[0m [1;33m.[0m[0m_tree[0m [1;32mimport[0m [0mPolicyTree[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [1;32mfrom[0m [1;33m.[0m[0m_forest[0m [1;32mimport[0m [0mPolicyForest[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\econml\policy\_forest\_tree.py[0m in [0;36m<module>[1;34m[0m
[0;32m     18[0m [1;32mfrom[0m [1;33m...[0m[0mtree[0m [1;32mimport[0m [0mDepthFirstTreeBuilder[0m[1;33m[0m[1;33m[0m[0m
[0;32m     19[0m [1;32mfrom[0m [1;33m...[0m[0mtree[0m [1;32mimport[0m [0m_tree[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 20[1;33m [1;32mfrom[0m [1;33m...[0m[0m_tree_exporter[0m [1;32mimport[0m [0m_SingleTreeExporterMixin[0m[1;33m,[0m [0m_PolicyTreeDOTExporter[0m[1;33m,[0m [0m_PolicyTreeMPLExporter[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     21[0m [1;32mfrom[0m [1;33m.[0m[0m_criterion[0m [1;32mimport[0m [0mLinearPolicyCriterion[0m[1;33m[0m[1;33m[0m[0m
[0;32m     22[0m [1;32mfrom[0m [1;33m.[0m [1;32mimport[0m [0m_criterion[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\econml\_tree_exporter.py[0m in [0;36m<module>[1;34m[0m
[0;32m     29[0m [1;33m[0m[0m
[0;32m     30[0m [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 31[1;33m     [1;32mimport[0m [0mgraphviz[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     32[0m [1;32mexcept[0m [0mImportError[0m [1;32mas[0m [0mexn[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     33[0m     [1;32mfrom[0m [1;33m.[0m[0mutilities[0m [1;32mimport[0m [0mMissingModule[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\graphviz\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m     25[0m """
[0;32m     26[0m [1;33m[0m[0m
[1;32m---> 27[1;33m [1;32mfrom[0m [1;33m.[0m[0mdot[0m [1;32mimport[0m [0mGraph[0m[1;33m,[0m [0mDigraph[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     28[0m [1;32mfrom[0m [1;33m.[0m[0mfiles[0m [1;32mimport[0m [0mSource[0m[1;33m[0m[1;33m[0m[0m
[0;32m     29[0m [1;32mfrom[0m [1;33m.[0m[0mlang[0m [1;32mimport[0m [0mescape[0m[1;33m,[0m [0mnohtml[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\graphviz\dot.py[0m in [0;36m<module>[1;34m[0m
[0;32m     30[0m [1;33m[0m[0m
[0;32m     31[0m [1;32mfrom[0m [1;33m.[0m [1;32mimport[0m [0mbackend[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 32[1;33m [1;32mfrom[0m [1;33m.[0m [1;32mimport[0m [0mfiles[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     33[0m [1;32mfrom[0m [1;33m.[0m [1;32mimport[0m [0mlang[0m[1;33m[0m[1;33m[0m[0m
[0;32m     34[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\graphviz\files.py[0m in [0;36m<module>[1;34m[0m
[0;32m     20[0m [1;33m[0m[0m
[0;32m     21[0m [1;33m[0m[0m
[1;32m---> 22[1;33m [1;32mclass[0m [0mBase[0m[1;33m([0m[0mobject[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     23[0m [1;33m[0m[0m
[0;32m     24[0m     [0m_engine[0m [1;33m=[0m [1;34m'dot'[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\graphviz\files.py[0m in [0;36mBase[1;34m()[0m
[0;32m     26[0m     [0m_format[0m [1;33m=[0m [1;34m'pdf'[0m[1;33m[0m[1;33m[0m[0m
[0;32m     27[0m [1;33m[0m[0m
[1;32m---> 28[1;33m     [0m_encoding[0m [1;33m=[0m [0mbackend[0m[1;33m.[0m[0mENCODING[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     29[0m [1;33m[0m[0m
[0;32m     30[0m     [1;33m@[0m[0mproperty[0m[1;33m[0m[1;33m[0m[0m

[1;31mAttributeError[0m: module 'graphviz.backend' has no attribute 'ENCODING'
AttributeError: module 'graphviz.backend' has no attribute 'ENCODING'

